# Generated by Django 2.1.7 on 2020-02-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_no', models.CharField(blank=True, max_length=10, null=True)),
                ('driver', models.CharField(blank=True, max_length=30)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('private_notes', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
