# Generated by Django 2.1.7 on 2020-02-05 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0003_auto_20200205_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_calls',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_calls',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='t_calls',
            name='user',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
