# Generated by Django 2.1.7 on 2020-02-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0004_auto_20200205_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(max_length=30)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('user', models.IntegerField(blank=True, default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_calls',
            name='rootid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud_ajax.t_staff'),
            preserve_default=False,
        ),
    ]
