# Generated by Django 2.1.7 on 2020-02-09 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0005_auto_20200209_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_calls',
            name='rootid',
        ),
    ]
