# Generated by Django 3.0.4 on 2020-03-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0007_t_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_staff',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
