# Generated by Django 3.0.4 on 2020-03-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0009_auto_20200319_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_staff',
            new_name='t_acct',
        ),
    ]
